dancingtogether/urls.py
from django.contrib import admin
from django.urls import include, path

import accounts.views
import main.views

urlpatterns = [
    path("", main.views.index, name="homepage"),
    path("about/", main.views.about, name="about"),
    path("contact/", main.views.contact, name="contact"),
    path("accounts/", include("accounts.urls")),
    path("admin/", admin.site.urls),
    path("join/", accounts.views.JoinView.as_view(), name="join"),
    path("login/", accounts.views.LoginView.as_view(), name="login"),
    path("logout/", accounts.views.LogoutView.as_view(), name="logout"),
    path("api/v1/", include("radio.api.urls")),
    path("stations/", include("radio.urls", namespace="radio")),
]

radio/urls.py
from django.urls import path

from . import views

app_name = "radio"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailStationView.as_view(), name="detail"),
    path("<int:pk>/delete/", views.DeleteStationView.as_view(), name="delete"),
    path("request-authorization-callback", views.oauth_callback),
]

templates/base.html
{% extends 'bootstrap4/bootstrap4.html' %}

{% block bootstrap4_title %}{% block title %}{% endblock %}{% endblock %}

{% load bootstrap4 %}
{% load static %}

{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% block bootstrap4_extra_head %}
    <link href="{% static "css/main.css" %}" rel="stylesheet"></link>
    <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
{% endblock %}

{% block bootstrap4_content %}

<header>
    <div class="row flex-nowrap justify-content-between align-items-center" id="primary-header">
        <div class="col-12 text-center">
            <a class="text-white" href="{% url 'homepage' %}" id="title">DANCING TOGETHER</a>
        </div>
    </div>

    <div class="nav-scroller py-1 mb-2" id="secondary-header">
        <nav class="nav d-flex justify-content-between">
            <a class="p-2 text-white" href="{% url 'homepage' %}">HOME</a>
            <a class="p-2 text-white" href="{% url 'about' %}">ABOUT</a>
            <a class="p-2 text-white" href="{% url 'radio:index' %}">LISTEN</a>
            <a class="p-2 text-white" href="{% url 'contact' %}">CONTACT</a>
            {% if user.is_authenticated %}
            <div class="ml-auto p-2 dropdown">
                <a class="text-white dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Account
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                    <span class="dropdown-item">Signed in as {{ user.username }}</span>
                    <a class="dropdown-item" href="{% url 'account-detail' user.id %}">Your profile</a>
                    <a class="dropdown-item" href="{% url 'logout' %}">Sign out</a>
                </div>
            </div>
            {% else %}
            <a class="ml-auto p-2 text-white" href="{% url 'login' %}">LOGIN</a>
            <a class="p-2 text-white" href="{% url 'join' %}">SIGN UP</a>
            {% endif %}
        </nav>
    </div>
</header>

<div class="container">
    {% block content %}{% endblock %}
</div>

<footer class="footer">
    <div class="container">
        <div class="copyright">&copy;2018 - <strong>DANCING TOGETHER</strong></div>
    </div>
</footer>

{% endblock %} {# bootstrap4_content#}

{% block bootstrap4_extra_script %}

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
{% comment %}
HACK: Include bootstrap.min.js again (already included in
'bootstrap_javascript' above) to get navbar toggler working.
See https://github.com/rgardner/dancingtogether/issues/1
{% endcomment %}
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

{% block extra_script %}{% endblock %}

{% endblock %}